<style  type="text/css"> 
cool {
  width: 100px;
  height: 100px;
  background-color: red;
  position: relative;
  -webkit-animation-name: example; /* Safari 4.0 - 8.0 */
  -webkit-animation-duration: 4s; /* Safari 4.0 - 8.0 */
  -webkit-animation-iteration-count: infinite; /* Safari 4.0 - 8.0 */
  animation-name: example;
  animation-duration: 4s;
  animation-iteration-count: infinite;
}

/* Safari 4.0 - 8.0 */
@-webkit-keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}

/* Standard syntax */
@keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}


}

</style>

<b><center>
    <span style="font-size: 24pt; line-height: 1.2;">COMS W4111: Introduction to Databases</span><br>
    <span style="font-size: 24pt; line-height: 1.2;">003/V03, Fall, 2022</span><br>
</center></b>
<br><br>
<i><center>
<span style="font-size: 20pt; line-height: 1.2;">Lecture 10 Examples</span>
</center></i>

<br><br>

# MySQL

In [1]:
%load_ext sql

In [2]:
%sql mysql+pymysql://root:dbuserdbuser@localhost

# MongoDB

In [3]:
import json

In [4]:
with open ("./secrets.json", "r") as in_file:
    secs = json.load(in_file)

## Connect to MongoDB

In [5]:
from pymongo import MongoClient

In [6]:
mongo_conn = MongoClient(
    secs["mongodb_atlas"]
)

- Test the connection ...

In [7]:
# What databases do we have?
print("We have the following databases in this server:")
for d in mongo_conn.list_database_names():
    print("\t", d)

We have the following databases in this server:
	 GoT
	 GoTR
	 classicmodels
	 cool_db
	 mydb
	 mydbd
	 s22_final
	 sss
	 xc2601
	 xc2601_final
	 zz2870
	 zz2870_final
	 admin
	 local

## Classic Models

### Simple Orders

- I want to access information about ```orderNumber``` 10101.


- In SQL, ... ...

In [8]:
%%sql

select * from classicmodels.orders join classicmodels.orderdetails
    using(orderNumber)
    where
        orderNumber=10101

 * mysql+pymysql://root:***@localhost
4 rows affected.

[(10101, datetime.date(2003, 1, 9), datetime.date(2003, 1, 18), datetime.date(2003, 1, 11), 'Shipped', 'Check on availability.', 128, 'S18_2325', 25, Decimal('108.06'), 4),
 (10101, datetime.date(2003, 1, 9), datetime.date(2003, 1, 18), datetime.date(2003, 1, 11), 'Shipped', 'Check on availability.', 128, 'S18_2795', 26, Decimal('167.06'), 1),
 (10101, datetime.date(2003, 1, 9), datetime.date(2003, 1, 18), datetime.date(2003, 1, 11), 'Shipped', 'Check on availability.', 128, 'S24_1937', 45, Decimal('32.53'), 3),
 (10101, datetime.date(2003, 1, 9), datetime.date(2003, 1, 18), datetime.date(2003, 1, 11), 'Shipped', 'Check on availability.', 128, 'S24_2022', 46, Decimal('44.35'), 2)]

- I think of the ```order``` containing the ```orderdetails,``` not "referencing" them.


- In MongoDB ... ...

In [16]:
collection = mongo_conn['classicmodels']['ordersall']

In [17]:
order = collection.find()

In [18]:
print(json.dumps(order, indent=3, default=str))

"<pymongo.cursor.Cursor object at 0x7fc09a105280>"

In [19]:
order_list = list(order)

In [20]:
order_list[0:5]

[{'_id': ObjectId('6238bdc4dbfa1c05c4e69dee'),
  'orderNumber': 10100,
  'orderDate': '2003-01-06',
  'requiredDate': '2003-01-13',
  'shippedDate': '2003-01-10',
  'status': 'Shipped',
  'customerNumber': 363,
  'orderLines': [{'productCode': 'S24_3969',
    'quantityOrdered': 49,
    'priceEach': 35.29},
   {'productCode': 'S18_2248', 'quantityOrdered': 50, 'priceEach': 55.09},
   {'productCode': 'S18_1749', 'quantityOrdered': 30, 'priceEach': 136.0},
   {'productCode': 'S18_4409', 'quantityOrdered': 22, 'priceEach': 75.46}],
  'comments': []},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69def'),
  'orderNumber': 10101,
  'orderDate': '2003-01-09',
  'requiredDate': '2003-01-18',
  'shippedDate': '2003-01-11',
  'status': 'Shipped',
  'customerNumber': 128,
  'orderLines': [{'productCode': 'S18_2795',
    'quantityOrdered': 26,
    'priceEach': 167.06},
   {'productCode': 'S24_2022', 'quantityOrdered': 46, 'priceEach': 44.35},
   {'productCode': 'S24_1937', 'quantityOrdered': 45, 'priceEach': 32.53},
   {'productCode': 'S18_2325', 'quantityOrdered': 25, 'priceEach': 108.06}],
  'comments': ['Check on availability.']},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69df0'),
  'orderNumber': 10102,
  'orderDate': '2003-01-10',
  'requiredDate': '2003-01-18',
  'shippedDate': '2003-01-14',
  'status': 'Shipped',
  'customerNumber': 181,
  'orderLines': [{'productCode': 'S18_1367',
    'quantityOrdered': 41,
    'priceEach': 43.13},
   {'productCode': 'S18_1342', 'quantityOrdered': 39, 'priceEach': 95.55}],
  'comments': []},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69df1'),
  'orderNumber': 10103,
  'orderDate': '2003-01-29',
  'requiredDate': '2003-02-07',
  'shippedDate': '2003-02-02',
  'status': 'Shipped',
  'customerNumber': 121,
  'orderLines': [{'productCode': 'S24_2300',
    'quantityOrdered': 36,
    'priceEach': 107.34},
   {'productCode': 'S18_2432', 'quantityOrdered': 22, 'priceEach': 58.34},
   {'productCode': 'S32_1268', 'quantityOrdered': 31, 'priceEach': 92.46},
   {'productCode': 'S10_4962', 'quantityOrdered': 42, 'priceEach': 119.67},
   {'productCode': 'S18_4600', 'quantityOrdered': 36, 'priceEach': 98.07},
   {'productCode': 'S700_2824', 'quantityOrdered': 42, 'priceEach': 94.07},
   {'productCode': 'S32_3522', 'quantityOrdered': 45, 'priceEach': 63.35},
   {'productCode': 'S12_1666', 'quantityOrdered': 27, 'priceEach': 121.64},
   {'productCode': 'S18_4668', 'quantityOrdered': 41, 'priceEach': 40.75},
   {'productCode': 'S18_1097', 'quantityOrdered': 35, 'priceEach': 94.5},
   {'productCode': 'S10_1949', 'quantityOrdered': 26, 'priceEach': 214.3},
   {'productCode': 'S18_2949', 'quantityOrdered': 27, 'priceEach': 92.19},
   {'productCode': 'S18_3136', 'quantityOrdered': 25, 'priceEach': 86.92},
   {'productCode': 'S18_2957', 'quantityOrdered': 35, 'priceEach': 61.84},
   {'productCode': 'S24_4258', 'quantityOrdered': 25, 'priceEach': 88.62},
   {'productCode': 'S18_3320', 'quantityOrdered': 46, 'priceEach': 86.31}],
  'comments': []},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69df2'),
  'orderNumber': 10104,
  'orderDate': '2003-01-31',
  'requiredDate': '2003-02-09',
  'shippedDate': '2003-02-01',
  'status': 'Shipped',
  'customerNumber': 141,
  'orderLines': [{'productCode': 'S12_3148',
    'quantityOrdered': 34,
    'priceEach': 131.44},
   {'productCode': 'S50_1514', 'quantityOrdered': 32, 'priceEach': 53.31},
   {'productCode': 'S18_4027', 'quantityOrdered': 38, 'priceEach': 119.2},
   {'productCode': 'S32_3207', 'quantityOrdered': 49, 'priceEach': 56.55},
   {'productCode': 'S24_4048', 'quantityOrdered': 26, 'priceEach': 106.45},
   {'productCode': 'S24_1444', 'quantityOrdered': 35, 'priceEach': 52.02},
   {'productCode': 'S50_1392', 'quantityOrdered': 33, 'priceEach': 114.59},
   {'productCode': 'S18_2238', 'quantityOrdered': 24, 'priceEach': 135.9},
   {'productCode': 'S12_4473', 'quantityOrdered': 41, 'priceEach': 111.39},
   {'productCode': 'S24_2840', 'quantityOrdered': 44, 'priceEach': 30.41},
   {'productCode': 'S32_2509', 'quantityOrdered': 35, 'priceEach': 51.95},
   {'productCode': 'S18_2319', 'quantityOrdered': 29, 'priceEach': 122.73},
   {'productCode': 'S18_3232', 'quantityOrdered': 23, 'priceEach': 165.95}],
  'comments': []}]

- Let's find all orders that contain ```productCode``` ```S18_2325```

In [21]:
filter={
    'orderLines.productCode': 'S18_2325'
}
project={
    'orderNumber': 1, 
    'orderLines': 1
}

In [22]:
result = collection.find(
    filter,
    project
)

In [23]:
list(result)

[{'_id': ObjectId('6238bdc4dbfa1c05c4e69def'),
  'orderNumber': 10101,
  'orderLines': [{'productCode': 'S18_2795',
    'quantityOrdered': 26,
    'priceEach': 167.06},
   {'productCode': 'S24_2022', 'quantityOrdered': 46, 'priceEach': 44.35},
   {'productCode': 'S24_1937', 'quantityOrdered': 45, 'priceEach': 32.53},
   {'productCode': 'S18_2325', 'quantityOrdered': 25, 'priceEach': 108.06}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69df8'),
  'orderNumber': 10110,
  'orderLines': [{'productCode': 'S18_2795',
    'quantityOrdered': 31,
    'priceEach': 163.69},
   {'productCode': 'S24_2022', 'quantityOrdered': 39, 'priceEach': 40.77},
   {'productCode': 'S24_1937', 'quantityOrdered': 20, 'priceEach': 28.88},
   {'productCode': 'S18_2325', 'quantityOrdered': 33, 'priceEach': 115.69},
   {'productCode': 'S24_3969', 'quantityOrdered': 48, 'priceEach': 35.29},
   {'productCode': 'S18_2248', 'quantityOrdered': 32, 'priceEach': 51.46},
   {'productCode': 'S18_1749', 'quantityOrdered': 42, 'priceEach': 153.0},
   {'productCode': 'S18_4409', 'quantityOrdered': 28, 'priceEach': 81.91},
   {'productCode': 'S18_4933', 'quantityOrdered': 42, 'priceEach': 62.0},
   {'productCode': 'S24_2887', 'quantityOrdered': 46, 'priceEach': 112.74},
   {'productCode': 'S24_2766', 'quantityOrdered': 43, 'priceEach': 82.69},
   {'productCode': 'S24_3191', 'quantityOrdered': 27, 'priceEach': 80.47},
   {'productCode': 'S24_1046', 'quantityOrdered': 36, 'priceEach': 72.02},
   {'productCode': 'S24_3432', 'quantityOrdered': 37, 'priceEach': 96.37},
   {'productCode': 'S24_1628', 'quantityOrdered': 29, 'priceEach': 43.27},
   {'productCode': 'S18_1589', 'quantityOrdered': 37, 'priceEach': 118.22}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e06'),
  'orderNumber': 10124,
  'orderLines': [{'productCode': 'S24_2022',
    'quantityOrdered': 22,
    'priceEach': 36.29},
   {'productCode': 'S24_1937', 'quantityOrdered': 45, 'priceEach': 30.53},
   {'productCode': 'S18_2325', 'quantityOrdered': 42, 'priceEach': 111.87},
   {'productCode': 'S24_3969', 'quantityOrdered': 46, 'priceEach': 36.11},
   {'productCode': 'S18_2248', 'quantityOrdered': 42, 'priceEach': 58.12},
   {'productCode': 'S18_1749', 'quantityOrdered': 21, 'priceEach': 153.0},
   {'productCode': 'S18_4409', 'quantityOrdered': 36, 'priceEach': 75.46},
   {'productCode': 'S18_4933', 'quantityOrdered': 23, 'priceEach': 66.28},
   {'productCode': 'S24_2887', 'quantityOrdered': 25, 'priceEach': 93.95},
   {'productCode': 'S24_2766', 'quantityOrdered': 32, 'priceEach': 74.51},
   {'productCode': 'S24_3191', 'quantityOrdered': 49, 'priceEach': 76.19},
   {'productCode': 'S24_1046', 'quantityOrdered': 22, 'priceEach': 62.47},
   {'productCode': 'S24_3432', 'quantityOrdered': 43, 'priceEach': 101.73}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e14'),
  'orderNumber': 10138,
  'orderLines': [{'productCode': 'S24_2022',
    'quantityOrdered': 33,
    'priceEach': 38.53},
   {'productCode': 'S24_1937', 'quantityOrdered': 22, 'priceEach': 33.19},
   {'productCode': 'S18_2325', 'quantityOrdered': 38, 'priceEach': 114.42},
   {'productCode': 'S24_3969', 'quantityOrdered': 29, 'priceEach': 32.82},
   {'productCode': 'S18_2248', 'quantityOrdered': 22, 'priceEach': 51.46},
   {'productCode': 'S18_1749', 'quantityOrdered': 33, 'priceEach': 149.6},
   {'productCode': 'S18_4409', 'quantityOrdered': 47, 'priceEach': 79.15},
   {'productCode': 'S18_4933', 'quantityOrdered': 23, 'priceEach': 64.86},
   {'productCode': 'S24_2887', 'quantityOrdered': 30, 'priceEach': 96.3},
   {'productCode': 'S24_2766', 'quantityOrdered': 28, 'priceEach': 73.6},
   {'productCode': 'S24_3191', 'quantityOrdered': 49, 'priceEach': 77.05},
   {'productCode': 'S24_1046', 'quantityOrdered': 45, 'priceEach': 59.53},
   {'productCode': 'S24_3432', 'quantityOrdered': 21, 'priceEach': 99.58}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e1f'),
  'orderNumber': 10149,
  'orderLines': [{'productCode': 'S24_4258',
    'quantityOrdered': 20,
    'priceEach': 90.57},
   {'productCode': 'S18_3320', 'quantityOrdered': 42, 'priceEach': 89.29},
   {'productCode': 'S18_1367', 'quantityOrdered': 30, 'priceEach': 48.52},
   {'productCode': 'S18_1342', 'quantityOrdered': 50, 'priceEach': 87.33},
   {'productCode': 'S18_2795', 'quantityOrdered': 23, 'priceEach': 167.06},
   {'productCode': 'S24_2022', 'quantityOrdered': 49, 'priceEach': 39.87},
   {'productCode': 'S24_1937', 'quantityOrdered': 36, 'priceEach': 31.2},
   {'productCode': 'S18_2325', 'quantityOrdered': 33, 'priceEach': 125.86},
   {'productCode': 'S24_3969', 'quantityOrdered': 26, 'priceEach': 38.57},
   {'productCode': 'S18_2248', 'quantityOrdered': 24, 'priceEach': 50.85},
   {'productCode': 'S18_1749', 'quantityOrdered': 34, 'priceEach': 156.4}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e2c'),
  'orderNumber': 10162,
  'orderLines': [{'productCode': 'S18_1367',
    'quantityOrdered': 45,
    'priceEach': 45.28},
   {'productCode': 'S18_1342', 'quantityOrdered': 48, 'priceEach': 87.33},
   {'productCode': 'S18_2795', 'quantityOrdered': 48, 'priceEach': 156.94},
   {'productCode': 'S24_2022', 'quantityOrdered': 43, 'priceEach': 38.98},
   {'productCode': 'S24_1937', 'quantityOrdered': 37, 'priceEach': 27.55},
   {'productCode': 'S18_2325', 'quantityOrdered': 38, 'priceEach': 113.15},
   {'productCode': 'S24_3969', 'quantityOrdered': 37, 'priceEach': 32.82},
   {'productCode': 'S18_2248', 'quantityOrdered': 27, 'priceEach': 53.28},
   {'productCode': 'S18_1749', 'quantityOrdered': 29, 'priceEach': 141.1},
   {'productCode': 'S18_4409', 'quantityOrdered': 39, 'priceEach': 86.51}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e37'),
  'orderNumber': 10173,
  'orderLines': [{'productCode': 'S18_3136',
    'quantityOrdered': 31,
    'priceEach': 86.92},
   {'productCode': 'S18_2957', 'quantityOrdered': 28, 'priceEach': 56.84},
   {'productCode': 'S24_4258', 'quantityOrdered': 22, 'priceEach': 93.49},
   {'productCode': 'S18_3320', 'quantityOrdered': 29, 'priceEach': 90.28},
   {'productCode': 'S18_1367', 'quantityOrdered': 48, 'priceEach': 51.75},
   {'productCode': 'S18_1342', 'quantityOrdered': 43, 'priceEach': 101.71},
   {'productCode': 'S18_2795', 'quantityOrdered': 22, 'priceEach': 140.06},
   {'productCode': 'S24_2022', 'quantityOrdered': 27, 'priceEach': 39.42},
   {'productCode': 'S24_1937', 'quantityOrdered': 31, 'priceEach': 29.87},
   {'productCode': 'S18_2325', 'quantityOrdered': 31, 'priceEach': 127.13},
   {'productCode': 'S24_3969', 'quantityOrdered': 35, 'priceEach': 35.7},
   {'productCode': 'S18_2248', 'quantityOrdered': 26, 'priceEach': 55.09},
   {'productCode': 'S18_1749', 'quantityOrdered': 24, 'priceEach': 168.3},
   {'productCode': 'S18_4409', 'quantityOrdered': 21, 'priceEach': 77.31},
   {'productCode': 'S18_4933', 'quantityOrdered': 39, 'priceEach': 58.44},
   {'productCode': 'S24_2887', 'quantityOrdered': 23, 'priceEach': 98.65}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e40'),
  'orderNumber': 10182,
  'orderLines': [{'productCode': 'S18_3320',
    'quantityOrdered': 33,
    'priceEach': 86.31},
   {'productCode': 'S18_1367', 'quantityOrdered': 32, 'priceEach': 44.21},
   {'productCode': 'S18_1342', 'quantityOrdered': 25, 'priceEach': 83.22},
   {'productCode': 'S18_2795', 'quantityOrdered': 21, 'priceEach': 135.0},
   {'productCode': 'S24_2022', 'quantityOrdered': 31, 'priceEach': 39.87},
   {'productCode': 'S24_1937', 'quantityOrdered': 39, 'priceEach': 31.86},
   {'productCode': 'S18_2325', 'quantityOrdered': 20, 'priceEach': 105.52},
   {'productCode': 'S24_3969', 'quantityOrdered': 23, 'priceEach': 34.88},
   {'productCode': 'S18_2248', 'quantityOrdered': 38, 'priceEach': 54.49},
   {'productCode': 'S18_1749', 'quantityOrdered': 44, 'priceEach': 159.8},
   {'productCode': 'S18_4409', 'quantityOrdered': 36, 'priceEach': 88.35},
   {'productCode': 'S18_4933', 'quantityOrdered': 44, 'priceEach': 61.29},
   {'productCode': 'S24_2887', 'quantityOrdered': 20, 'priceEach': 116.27},
   {'productCode': 'S24_2766', 'quantityOrdered': 36, 'priceEach': 87.24},
   {'productCode': 'S24_3191', 'quantityOrdered': 33, 'priceEach': 73.62},
   {'productCode': 'S24_1046', 'quantityOrdered': 47, 'priceEach': 63.2},
   {'productCode': 'S24_3432', 'quantityOrdered': 49, 'priceEach': 95.3}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e4b'),
  'orderNumber': 10193,
  'orderLines': [{'productCode': 'S18_2949',
    'quantityOrdered': 28,
    'priceEach': 87.13},
   {'productCode': 'S18_3136', 'quantityOrdered': 23, 'priceEach': 97.39},
   {'productCode': 'S18_2957', 'quantityOrdered': 24, 'priceEach': 53.09},
   {'productCode': 'S24_4258', 'quantityOrdered': 20, 'priceEach': 92.52},
   {'productCode': 'S18_3320', 'quantityOrdered': 32, 'priceEach': 79.37},
   {'productCode': 'S18_1367', 'quantityOrdered': 46, 'priceEach': 46.36},
   {'productCode': 'S18_1342', 'quantityOrdered': 28, 'priceEach': 92.47},
   {'productCode': 'S18_2795', 'quantityOrdered': 22, 'priceEach': 143.44},
   {'productCode': 'S24_2022', 'quantityOrdered': 20, 'priceEach': 44.8},
   {'productCode': 'S24_1937', 'quantityOrdered': 26, 'priceEach': 32.19},
   {'productCode': 'S18_2325', 'quantityOrdered': 44, 'priceEach': 115.69},
   {'productCode': 'S24_3969', 'quantityOrdered': 22, 'priceEach': 38.16},
   {'productCode': 'S18_2248', 'quantityOrdered': 42, 'priceEach': 60.54},
   {'productCode': 'S18_1749', 'quantityOrdered': 21, 'priceEach': 153.0},
   {'productCode': 'S18_4409', 'quantityOrdered': 24, 'priceEach': 92.03},
   {'productCode': 'S18_4933', 'quantityOrdered': 25, 'priceEach': 66.28}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e56'),
  'orderNumber': 10204,
  'orderLines': [{'productCode': 'S18_2325',
    'quantityOrdered': 26,
    'priceEach': 119.5},
   {'productCode': 'S24_3969', 'quantityOrdered': 39, 'priceEach': 34.88},
   {'productCode': 'S18_2248', 'quantityOrdered': 23, 'priceEach': 59.33},
   {'productCode': 'S18_1749', 'quantityOrdered': 33, 'priceEach': 153.0},
   {'productCode': 'S18_4409', 'quantityOrdered': 29, 'priceEach': 83.75},
   {'productCode': 'S18_4933', 'quantityOrdered': 45, 'priceEach': 69.84},
   {'productCode': 'S24_2887', 'quantityOrdered': 42, 'priceEach': 112.74},
   {'productCode': 'S24_2766', 'quantityOrdered': 47, 'priceEach': 79.06},
   {'productCode': 'S24_3191', 'quantityOrdered': 40, 'priceEach': 84.75},
   {'productCode': 'S24_1046', 'quantityOrdered': 20, 'priceEach': 69.82},
   {'productCode': 'S24_3432', 'quantityOrdered': 48, 'priceEach': 104.94},
   {'productCode': 'S24_1628', 'quantityOrdered': 45, 'priceEach': 46.79},
   {'productCode': 'S18_1589', 'quantityOrdered': 40, 'priceEach': 113.24},
   {'productCode': 'S18_2870', 'quantityOrdered': 27, 'priceEach': 106.92},
   {'productCode': 'S18_3685', 'quantityOrdered': 35, 'priceEach': 132.8},
   {'productCode': 'S18_1984', 'quantityOrdered': 38, 'priceEach': 133.72},
   {'productCode': 'S18_1129', 'quantityOrdered': 42, 'priceEach': 114.65}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e60'),
  'orderNumber': 10214,
  'orderLines': [{'productCode': 'S18_2795',
    'quantityOrdered': 50,
    'priceEach': 167.06},
   {'productCode': 'S24_2022', 'quantityOrdered': 49, 'priceEach': 39.87},
   {'productCode': 'S24_1937', 'quantityOrdered': 20, 'priceEach': 32.19},
   {'productCode': 'S18_2325', 'quantityOrdered': 27, 'priceEach': 125.86},
   {'productCode': 'S24_3969', 'quantityOrdered': 44, 'priceEach': 38.57},
   {'productCode': 'S18_2248', 'quantityOrdered': 21, 'priceEach': 53.28},
   {'productCode': 'S18_1749', 'quantityOrdered': 30, 'priceEach': 166.6}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e6d'),
  'orderNumber': 10227,
  'orderLines': [{'productCode': 'S18_3320',
    'quantityOrdered': 33,
    'priceEach': 99.21},
   {'productCode': 'S18_1367', 'quantityOrdered': 31, 'priceEach': 50.14},
   {'productCode': 'S18_1342', 'quantityOrdered': 25, 'priceEach': 85.27},
   {'productCode': 'S18_2795', 'quantityOrdered': 29, 'priceEach': 146.81},
   {'productCode': 'S24_2022', 'quantityOrdered': 24, 'priceEach': 39.42},
   {'productCode': 'S24_1937', 'quantityOrdered': 42, 'priceEach': 27.22},
   {'productCode': 'S18_2325', 'quantityOrdered': 46, 'priceEach': 118.23},
   {'productCode': 'S24_3969', 'quantityOrdered': 27, 'priceEach': 34.88},
   {'productCode': 'S18_2248', 'quantityOrdered': 28, 'priceEach': 59.93},
   {'productCode': 'S18_1749', 'quantityOrdered': 26, 'priceEach': 136.0},
   {'productCode': 'S18_4409', 'quantityOrdered': 34, 'priceEach': 87.43},
   {'productCode': 'S18_4933', 'quantityOrdered': 37, 'priceEach': 70.56},
   {'productCode': 'S24_2887', 'quantityOrdered': 33, 'priceEach': 102.17},
   {'productCode': 'S24_2766', 'quantityOrdered': 47, 'priceEach': 84.51},
   {'productCode': 'S24_3191', 'quantityOrdered': 40, 'priceEach': 78.76}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e7d'),
  'orderNumber': 10243,
  'orderLines': [{'productCode': 'S24_1937',
    'quantityOrdered': 33,
    'priceEach': 30.87},
   {'productCode': 'S18_2325', 'quantityOrdered': 47, 'priceEach': 111.87}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e88'),
  'orderNumber': 10254,
  'orderLines': [{'productCode': 'S24_1937',
    'quantityOrdered': 38,
    'priceEach': 28.88},
   {'productCode': 'S18_2325', 'quantityOrdered': 41, 'priceEach': 102.98},
   {'productCode': 'S24_3969', 'quantityOrdered': 20, 'priceEach': 39.8},
   {'productCode': 'S18_2248', 'quantityOrdered': 36, 'priceEach': 55.09},
   {'productCode': 'S18_1749', 'quantityOrdered': 49, 'priceEach': 137.7},
   {'productCode': 'S18_4409', 'quantityOrdered': 34, 'priceEach': 80.99},
   {'productCode': 'S18_4933', 'quantityOrdered': 30, 'priceEach': 59.87},
   {'productCode': 'S24_2887', 'quantityOrdered': 33, 'priceEach': 111.57},
   {'productCode': 'S24_2766', 'quantityOrdered': 31, 'priceEach': 85.42},
   {'productCode': 'S24_3191', 'quantityOrdered': 42, 'priceEach': 69.34},
   {'productCode': 'S24_1046', 'quantityOrdered': 34, 'priceEach': 66.88},
   {'productCode': 'S24_3432', 'quantityOrdered': 49, 'priceEach': 101.73},
   {'productCode': 'S24_1628', 'quantityOrdered': 32, 'priceEach': 43.27}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69e96'),
  'orderNumber': 10268,
  'orderLines': [{'productCode': 'S18_3320',
    'quantityOrdered': 39,
    'priceEach': 96.23},
   {'productCode': 'S18_1367', 'quantityOrdered': 26, 'priceEach': 45.82},
   {'productCode': 'S18_1342', 'quantityOrdered': 49, 'priceEach': 93.49},
   {'productCode': 'S18_2795', 'quantityOrdered': 35, 'priceEach': 148.5},
   {'productCode': 'S24_2022', 'quantityOrdered': 40, 'priceEach': 36.29},
   {'productCode': 'S24_1937', 'quantityOrdered': 33, 'priceEach': 31.86},
   {'productCode': 'S18_2325', 'quantityOrdered': 50, 'priceEach': 124.59},
   {'productCode': 'S24_3969', 'quantityOrdered': 30, 'priceEach': 37.75},
   {'productCode': 'S18_2248', 'quantityOrdered': 31, 'priceEach': 60.54},
   {'productCode': 'S18_1749', 'quantityOrdered': 34, 'priceEach': 164.9},
   {'productCode': 'S18_4409', 'quantityOrdered': 35, 'priceEach': 84.67}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69ea2'),
  'orderNumber': 10280,
  'orderLines': [{'productCode': 'S18_1097',
    'quantityOrdered': 24,
    'priceEach': 98.0},
   {'productCode': 'S10_1949', 'quantityOrdered': 34, 'priceEach': 205.73},
   {'productCode': 'S18_2949', 'quantityOrdered': 46, 'priceEach': 82.06},
   {'productCode': 'S18_3136', 'quantityOrdered': 29, 'priceEach': 102.63},
   {'productCode': 'S18_2957', 'quantityOrdered': 43, 'priceEach': 54.34},
   {'productCode': 'S24_4258', 'quantityOrdered': 21, 'priceEach': 79.86},
   {'productCode': 'S18_3320', 'quantityOrdered': 34, 'priceEach': 99.21},
   {'productCode': 'S18_1367', 'quantityOrdered': 27, 'priceEach': 47.44},
   {'productCode': 'S18_1342', 'quantityOrdered': 50, 'priceEach': 87.33},
   {'productCode': 'S18_2795', 'quantityOrdered': 22, 'priceEach': 158.63},
   {'productCode': 'S24_2022', 'quantityOrdered': 45, 'priceEach': 36.29},
   {'productCode': 'S24_1937', 'quantityOrdered': 20, 'priceEach': 29.87},
   {'productCode': 'S18_2325', 'quantityOrdered': 37, 'priceEach': 109.33},
   {'productCode': 'S24_3969', 'quantityOrdered': 33, 'priceEach': 35.29},
   {'productCode': 'S18_2248', 'quantityOrdered': 25, 'priceEach': 53.28},
   {'productCode': 'S18_1749', 'quantityOrdered': 26, 'priceEach': 161.5},
   {'productCode': 'S18_4409', 'quantityOrdered': 35, 'priceEach': 77.31}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69eaa'),
  'orderNumber': 10288,
  'orderLines': [{'productCode': 'S24_1937',
    'quantityOrdered': 29,
    'priceEach': 32.19},
   {'productCode': 'S18_2325', 'quantityOrdered': 31, 'priceEach': 102.98},
   {'productCode': 'S24_3969', 'quantityOrdered': 33, 'priceEach': 37.75},
   {'productCode': 'S18_2248', 'quantityOrdered': 28, 'priceEach': 50.25},
   {'productCode': 'S18_1749', 'quantityOrdered': 32, 'priceEach': 168.3},
   {'productCode': 'S18_4409', 'quantityOrdered': 35, 'priceEach': 90.19},
   {'productCode': 'S18_4933', 'quantityOrdered': 23, 'priceEach': 57.02},
   {'productCode': 'S24_2887', 'quantityOrdered': 48, 'priceEach': 109.22},
   {'productCode': 'S24_2766', 'quantityOrdered': 35, 'priceEach': 81.78},
   {'productCode': 'S24_3191', 'quantityOrdered': 34, 'priceEach': 76.19},
   {'productCode': 'S24_1046', 'quantityOrdered': 36, 'priceEach': 66.88},
   {'productCode': 'S24_3432', 'quantityOrdered': 41, 'priceEach': 101.73},
   {'productCode': 'S24_1628', 'quantityOrdered': 50, 'priceEach': 49.3},
   {'productCode': 'S18_1589', 'quantityOrdered': 20, 'priceEach': 120.71}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69eba'),
  'orderNumber': 10304,
  'orderLines': [{'productCode': 'S700_2824',
    'quantityOrdered': 40,
    'priceEach': 80.92},
   {'productCode': 'S32_3522', 'quantityOrdered': 36, 'priceEach': 52.36},
   {'productCode': 'S12_1666', 'quantityOrdered': 39, 'priceEach': 117.54},
   {'productCode': 'S18_4668', 'quantityOrdered': 34, 'priceEach': 44.27},
   {'productCode': 'S18_1097', 'quantityOrdered': 46, 'priceEach': 106.17},
   {'productCode': 'S10_1949', 'quantityOrdered': 47, 'priceEach': 201.44},
   {'productCode': 'S18_2949', 'quantityOrdered': 46, 'priceEach': 98.27},
   {'productCode': 'S18_3136', 'quantityOrdered': 26, 'priceEach': 90.06},
   {'productCode': 'S18_2957', 'quantityOrdered': 24, 'priceEach': 54.34},
   {'productCode': 'S24_4258', 'quantityOrdered': 33, 'priceEach': 80.83},
   {'productCode': 'S18_3320', 'quantityOrdered': 38, 'priceEach': 95.24},
   {'productCode': 'S18_1367', 'quantityOrdered': 37, 'priceEach': 46.9},
   {'productCode': 'S18_1342', 'quantityOrdered': 37, 'priceEach': 95.55},
   {'productCode': 'S18_2795', 'quantityOrdered': 20, 'priceEach': 141.75},
   {'productCode': 'S24_2022', 'quantityOrdered': 44, 'priceEach': 42.11},
   {'productCode': 'S24_1937', 'quantityOrdered': 23, 'priceEach': 29.21},
   {'productCode': 'S18_2325', 'quantityOrdered': 24, 'priceEach': 102.98}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69ec2'),
  'orderNumber': 10312,
  'orderLines': [{'productCode': 'S18_4668',
    'quantityOrdered': 39,
    'priceEach': 44.27},
   {'productCode': 'S18_1097', 'quantityOrdered': 32, 'priceEach': 101.5},
   {'productCode': 'S10_1949', 'quantityOrdered': 48, 'priceEach': 214.3},
   {'productCode': 'S18_2949', 'quantityOrdered': 37, 'priceEach': 91.18},
   {'productCode': 'S18_3136', 'quantityOrdered': 38, 'priceEach': 93.2},
   {'productCode': 'S18_2957', 'quantityOrdered': 35, 'priceEach': 54.34},
   {'productCode': 'S24_4258', 'quantityOrdered': 44, 'priceEach': 96.42},
   {'productCode': 'S18_3320', 'quantityOrdered': 33, 'priceEach': 84.33},
   {'productCode': 'S18_1367', 'quantityOrdered': 25, 'priceEach': 43.67},
   {'productCode': 'S18_1342', 'quantityOrdered': 43, 'priceEach': 102.74},
   {'productCode': 'S18_2795', 'quantityOrdered': 25, 'priceEach': 150.19},
   {'productCode': 'S24_2022', 'quantityOrdered': 23, 'priceEach': 43.46},
   {'productCode': 'S24_1937', 'quantityOrdered': 39, 'priceEach': 27.88},

- How about the ones with the ```quantityOrdered >= 20``` for  ```productCode``` ```S18_2325```

In [24]:
filter={
    'orderLines': {
        '$elemMatch': {
            'productCode': 'S18_2325', 
            'quantityOrdered': {
                '$gte': 50
            }
        }
    }
}
project={
    'orderNumber': 1, 
    'orderLines': 1
}

In [25]:
result = collection.find(
    filter,
    project
)

In [26]:
list(result)

[{'_id': ObjectId('6238bdc4dbfa1c05c4e69e96'),
  'orderNumber': 10268,
  'orderLines': [{'productCode': 'S18_3320',
    'quantityOrdered': 39,
    'priceEach': 96.23},
   {'productCode': 'S18_1367', 'quantityOrdered': 26, 'priceEach': 45.82},
   {'productCode': 'S18_1342', 'quantityOrdered': 49, 'priceEach': 93.49},
   {'productCode': 'S18_2795', 'quantityOrdered': 35, 'priceEach': 148.5},
   {'productCode': 'S24_2022', 'quantityOrdered': 40, 'priceEach': 36.29},
   {'productCode': 'S24_1937', 'quantityOrdered': 33, 'priceEach': 31.86},
   {'productCode': 'S18_2325', 'quantityOrdered': 50, 'priceEach': 124.59},
   {'productCode': 'S24_3969', 'quantityOrdered': 30, 'priceEach': 37.75},
   {'productCode': 'S18_2248', 'quantityOrdered': 31, 'priceEach': 60.54},
   {'productCode': 'S18_1749', 'quantityOrdered': 34, 'priceEach': 164.9},
   {'productCode': 'S18_4409', 'quantityOrdered': 35, 'priceEach': 84.67}]},
 {'_id': ObjectId('6238bdc4dbfa1c05c4e69ecc'),
  'orderNumber': 10322,
  'orderLines': [{'productCode': 'S10_1949',
    'quantityOrdered': 40,
    'priceEach': 180.01},
   {'productCode': 'S18_2795', 'quantityOrdered': 36, 'priceEach': 158.63},
   {'productCode': 'S24_1937', 'quantityOrdered': 20, 'priceEach': 26.55},
   {'productCode': 'S24_2022', 'quantityOrdered': 30, 'priceEach': 40.77},
   {'productCode': 'S18_1367', 'quantityOrdered': 41, 'priceEach': 44.21},
   {'productCode': 'S18_2325', 'quantityOrdered': 50, 'priceEach': 120.77},
   {'productCode': 'S18_3136', 'quantityOrdered': 48, 'priceEach': 90.06},
   {'productCode': 'S10_4962', 'quantityOrdered': 46, 'priceEach': 141.83},
   {'productCode': 'S12_1666', 'quantityOrdered': 27, 'priceEach': 136.67},
   {'productCode': 'S18_1097', 'quantityOrdered': 22, 'priceEach': 101.5},
   {'productCode': 'S18_2432', 'quantityOrdered': 35, 'priceEach': 57.12},
   {'productCode': 'S18_2949', 'quantityOrdered': 33, 'priceEach': 100.3},
   {'productCode': 'S18_2957', 'quantityOrdered': 41, 'priceEach': 54.34},
   {'productCode': 'S18_1342', 'quantityOrdered': 43, 'priceEach': 92.47}]}]

### Some Aggregations

- Let's do the famous "total revenue per customer!"


- This is an aggregation pipeline.

In [27]:
# Requires the PyMongo package.
# https://api.mongodb.com/python/current

result = collection.aggregate([
    {
        '$match': {
            'status': {
                '$nin': [
                    'Cancelled', 'On Hold', 'In Process'
                ]
            }
        }
    }, {
        '$unwind': {
            'path': '$orderLines', 
            'preserveNullAndEmptyArrays': True
        }
    }, {
        '$project': {
            'customerNumber': 1, 
            'orderNumber': 1, 
            'status': 1, 
            'quantityOrdered': '$orderLines.quantityOrdered', 
            'priceEach': '$orderLines.priceEach', 
            'lineValue': {
                '$multiply': [
                    '$orderLines.quantityOrdered', '$orderLines.priceEach'
                ]
            }
        }
    }, {
        '$group': {
            '_id': '$customerNumber', 
            'totalValue': {
                '$sum': '$lineValue'
            }
        }
    }, {
        '$project': {
            '_id': 0, 
            'customerNumber': '$_id', 
            'totalValue': 1
        }
    }, {
        '$sort': {
            'totalValue': -1
        }
    }
])

In [28]:
import pandas as pd

In [29]:
result = list(result)
result_df = pd.DataFrame(result)

In [30]:
result_df = result_df[['customerNumber', "totalValue"]]
result_df

    customerNumber  totalValue
0              141   744313.88
1              124   584188.24
2              114   180585.07
3              151   177913.95
4              148   156251.03
..             ...         ...
93             381    29217.18
94             473    25358.32
95             103    22314.36
96             198    21554.26
97             219     7918.60

[98 rows x 2 columns]

### Let's Load Some Data

In [31]:
customers = %sql select * from classicmodels.customers

 * mysql+pymysql://root:***@localhost
122 rows affected.

In [32]:
customers

[(103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370, Decimal('21000.00')),
 (112, 'Signal Gift Stores', 'King', 'Jean', '7025551838', '8489 Strong St.', None, 'Las Vegas', 'NV', '83030', 'USA', 1166, Decimal('71800.00')),
 (114, 'Australian Collectors, Co.', 'Ferguson', 'Peter', '03 9520 4555', '636 St Kilda Road', 'Level 3', 'Melbourne', 'Victoria', '3004', 'Australia', 1611, Decimal('117300.00')),
 (119, 'La Rochelle Gifts', 'Labrune', 'Janine ', '40.67.8555', '67, rue des Cinquante Otages', None, 'Nantes', None, '44000', 'France', 1370, Decimal('118200.00')),
 (121, 'Baane Mini Imports', 'Bergulfsen', 'Jonas ', '07-98 9555', 'Erling Skakkes gate 78', None, 'Stavern', None, '4110', 'Norway', 1504, Decimal('81700.00')),
 (124, 'Mini Gifts Distributors Ltd.', 'Nelson', 'Susan', '4155551450', '5677 Strong St.', None, 'San Rafael', 'CA', '97562', 'USA', 1165, Decimal('210500.00')),
 (125, 'Havel & Zbyszek Co', 'Piestrzeniewicz', 'Zbyszek ', '(26) 642-7555', 'ul. Filtrowa 68', None, 'Warszawa', None, '01-012', 'Poland', None, Decimal('0.00')),
 (128, 'Blauer See Auto, Co.', 'Keitel', 'Roland', '+49 69 66 90 2555', 'Lyonerstr. 34', None, 'Frankfurt', None, '60528', 'Germany', 1504, Decimal('59700.00')),
 (129, 'Mini Wheels Co.', 'Murphy', 'Julie', '6505555787', '5557 North Pendale Street', None, 'San Francisco', 'CA', '94217', 'USA', 1165, Decimal('64600.00')),
 (131, 'Land of Toys Inc.', 'Lee', 'Kwai', '2125557818', '897 Long Airport Avenue', None, 'NYC', 'NY', '10022', 'USA', 1323, Decimal('114900.00')),
 (141, 'Euro+ Shopping Channel', 'Freyre', 'Diego ', '(91) 555 94 44', 'C/ Moralzarzal, 86', None, 'Madrid', None, '28034', 'Spain', 1370, Decimal('227600.00')),
 (144, 'Volvo Model Replicas, Co', 'Berglund', 'Christina ', '0921-12 3555', 'Berguvsvägen  8', None, 'Luleå', None, 'S-958 22', 'Sweden', 1504, Decimal('53100.00')),
 (145, 'Danish Wholesale Imports', 'Petersen', 'Jytte ', '31 12 3555', 'Vinbæltet 34', None, 'Kobenhavn', None, '1734', 'Denmark', 1401, Decimal('83400.00')),
 (146, 'Saveley & Henriot, Co.', 'Saveley', 'Mary ', '78.32.5555', '2, rue du Commerce', None, 'Lyon', None, '69004', 'France', 1337, Decimal('123900.00')),
 (148, 'Dragon Souveniers, Ltd.', 'Natividad', 'Eric', '+65 221 7555', 'Bronz Sok.', 'Bronz Apt. 3/6 Tesvikiye', 'Singapore', None, '079903', 'Singapore', 1621, Decimal('103800.00')),
 (151, 'Muscle Machine Inc', 'Young', 'Jeff', '2125557413', '4092 Furth Circle', 'Suite 400', 'NYC', 'NY', '10022', 'USA', 1286, Decimal('138500.00')),
 (157, 'Diecast Classics Inc.', 'Leong', 'Kelvin', '2155551555', '7586 Pompton St.', None, 'Allentown', 'PA', '70267', 'USA', 1216, Decimal('100600.00')),
 (161, 'Technics Stores Inc.', 'Hashimoto', 'Juri', '6505556809', '9408 Furth Circle', None, 'Burlingame', 'CA', '94217', 'USA', 1165, Decimal('84600.00')),
 (166, 'Handji Gifts& Co', 'Victorino', 'Wendy', '+65 224 1555', '106 Linden Road Sandown', '2nd Floor', 'Singapore', None, '069045', 'Singapore', 1612, Decimal('97900.00')),
 (167, 'Herkku Gifts', 'Oeztan', 'Veysel', '+47 2267 3215', 'Brehmen St. 121', 'PR 334 Sentrum', 'Bergen', None, 'N 5804', 'Norway  ', 1504, Decimal('96800.00')),
 (168, 'American Souvenirs Inc', 'Franco', 'Keith', '2035557845', '149 Spinnaker Dr.', 'Suite 101', 'New Haven', 'CT', '97823', 'USA', 1286, Decimal('0.00')),
 (169, 'Porto Imports Co.', 'de Castro', 'Isabel ', '(1) 356-5555', 'Estrada da saúde n. 58', None, 'Lisboa', None, '1756', 'Portugal', None, Decimal('0.00')),
 (171, 'Daedalus Designs Imports', 'Rancé', 'Martine ', '20.16.1555', '184, chaussée de Tournai', None, 'Lille', None, '59000', 'France', 1370, Decimal('82900.00')),
 (172, "La Corne D'abondance, Co.", 'Bertrand', 'Marie', '(1) 42.34.2555', '265, boulevard Charonne', None, 'Paris', None, '75012', 'France', 1337, Decimal('84300.00')),
 (173, 'Cambridge Collectables Co.', 'Tseng', 'Jerry', '6175555555', '4658 Baden Av.', None, 'Cambridge', 'MA', '51247', 'USA', 1188, Decimal('43400.00')),
 (175, 'Gift Depot Inc.', 'King', 'Julie', '2035552570', '25593 South Bay Ln.', None, 'Bridgewater', 'CT', '97562', 'USA', 1323, Decimal('84300.00')),
 (177, 'Osaka Souveniers Co.', 'Kentary', 'Mory', '+81 06 6342 5555', '1-6-20 Dojima', None, 'Kita-ku', 'Osaka', ' 530-0003', 'Japan', 1621, Decimal('81200.00')),
 (181, 'Vitachrome Inc.', 'Frick', 'Michael', '2125551500', '2678 Kingston Rd.', 'Suite 101', 'NYC', 'NY', '10022', 'USA', 1286, Decimal('76400.00')),
 (186, 'Toys of Finland, Co.', 'Karttunen', 'Matti', '90-224 8555', 'Keskuskatu 45', None, 'Helsinki', None, '21240', 'Finland', 1501, Decimal('96500.00')),
 (187, 'AV Stores, Co.', 'Ashworth', 'Rachel', '(171) 555-1555', 'Fauntleroy Circus', None, 'Manchester', None, 'EC2 5NT', 'UK', 1501, Decimal('136800.00')),
 (189, 'Clover Collections, Co.', 'Cassidy', 'Dean', '+353 1862 1555', '25 Maiden Lane', 'Floor No. 4', 'Dublin', None, '2', 'Ireland', 1504, Decimal('69400.00')),
 (198, 'Auto-Moto Classics Inc.', 'Taylor', 'Leslie', '6175558428', '16780 Pompton St.', None, 'Brickhaven', 'MA', '58339', 'USA', 1216, Decimal('23000.00')),
 (201, 'UK Collectables, Ltd.', 'Devon', 'Elizabeth', '(171) 555-2282', '12, Berkeley Gardens Blvd', None, 'Liverpool', None, 'WX1 6LT', 'UK', 1501, Decimal('92700.00')),
 (202, 'Canadian Gift Exchange Network', 'Tamuri', 'Yoshi ', '(604) 555-3392', '1900 Oak St.', None, 'Vancouver', 'BC', 'V3F 2K1', 'Canada', 1323, Decimal('90300.00')),
 (204, 'Online Mini Collectables', 'Barajas', 'Miguel', '6175557555', '7635 Spinnaker Dr.', None, 'Brickhaven', 'MA', '58339', 'USA', 1188, Decimal('68700.00')),
 (205, 'Toys4GrownUps.com', 'Young', 'Julie', '6265557265', '78934 Hillside Dr.', None, 'Pasadena', 'CA', '90003', 'USA', 1166, Decimal('90700.00')),
 (206, 'Asian Shopping Network, Co', 'Walker', 'Brydey', '+612 9411 1555', 'Suntec Tower Three', '8 Temasek', 'Singapore', None, '038988', 'Singapore', None, Decimal('0.00')),
 (209, 'Mini Caravy', 'Citeaux', 'Frédérique ', '88.60.1555', '24, place Kléber', None, 'Strasbourg', None, '67000', 'France', 1370, Decimal('53800.00')),
 (211, 'King Kong Collectables, Co.', 'Gao', 'Mike', '+852 2251 1555', 'Bank of China Tower', '1 Garden Road', 'Central Hong Kong', None, None, 'Hong Kong', 1621, Decimal('58600.00')),
 (216, 'Enaco Distributors', 'Saavedra', 'Eduardo ', '(93) 203 4555', 'Rambla de Cataluña, 23', None, 'Barcelona', None, '08022', 'Spain', 1702, Decimal('60300.00')),
 (219, 'Boards & Toys Co.', 'Young', 'Mary', '3105552373', '4097 Douglas Av.', None, 'Glendale', 'CA', '92561', 'USA', 1166, Decimal('11000.00')),
 (223, 'Natürlich Autos', 'Kloss', 'Horst ', '0372-555188', 'Taucherstraße 10', None, 'Cunewalde', None, '01307', 'Germany', None, Decimal('0.00')),
 (227, 'Heintze Collectables', 'Ibsen', 'Palle', '86 21 3555', 'Smagsloget 45', None, 'Århus', None, '8200', 'Denmark', 1401, Decimal('120800.00')),
 (233, 'Québec Home Shopping Network', 'Fresnière', 'Jean ', '(514) 555-8054', '43 rue St. Laurent', None, 'Montréal', 'Québec', 'H1J 1C3', 'Canada', 1286, Decimal('48700.00')),
 (237, 'ANG Resellers', 'Camino', 'Alejandra ', '(91) 745 6555', 'Gran Vía, 1', None, 'Madrid', None, '28001', 'Spain', None, Decimal('0.00')),
 (239, 'Collectable Mini Designs Co.', 'Thompson', 'Valarie', '7605558146', '361 Furth Circle', None, 'San Diego', 'CA', '91217', 'USA', 1166, Decimal('105000.00')),
 (240, 'giftsbymail.co.uk', 'Bennett', 'Helen ', '(198) 555-8888', 'Garden House', 'Crowther Way 23', 'Cowes', 'Isle of Wight', 'PO31 7PJ', 'UK', 1501, Decimal('93900.00')),
 (242, 'Alpha Cognac', 'Roulet', 'Annette ', '61.77.6555', '1 rue Alsace-Lorraine', None, 'Toulouse', None, '31000', 'France', 1370, Decimal('61100.00')),
 (247, 'Messner Shopping Network', 'Messner', 'Renate ', '069-0555984', 'Magazinweg 7', None, 'Frankfurt', None, '60528', 'Germany', None, Decimal('0.00')),
 (249, 'Amica Models & Co.', 'Accorti', 'Paolo ', '011-4988555', 'Via Monte Bianco 34', None, 'Torino', None, '10100', 'Italy', 1401, Decimal('113000.00')),
 (250, 'Lyon Souveniers', 'Da Silva', 'Daniel', '+33 1 46 62 7555', '27 rue du Colonel Pierre Avia', None, 'Paris', None, '75508', 'France', 1337, Decimal('68100.00')),
 (256, 'Auto Associés & Cie.', 'Tonini', 'Daniel ', '30.59.8555', "67, avenue de l'Europe", None, 'Versailles', None, '78000', 'France', 1370, Decimal('77900.00')),
 (259, 'Toms Spezialitäten, Ltd', 'Pfalzheim', 'Henriette ', '0221-5554327', 'Mehrheimerstr. 369', None, 'Köln', None, '50739', 'Germany', 1504, Decimal('120400.00')),
 (260, 'Royal Canadian Collectables, Ltd.', 'Lincoln', 'Elizabeth ', '(604) 555-4555', '23 Tsawassen Blvd.', None, 'Tsawassen', 'BC', 'T2F 8M4', 'Canada', 1323, Decimal('89600.00')),
 (273, 'Franken Gifts, Co', 'Franken', 'Peter ', '089-0877555', 'Berliner Platz 43', None, 'München', None, '80805', 'Germany', None, Decimal('0.00')),
 (276, "Anna's Decorations, Ltd", "O'Hara", 'Anna', '02 9936 8555', '201 Miller Street', 'Level 15', 'North Sydney', 'NSW', '2060', 'Australia', 1611, Decimal('107800.00')),
 (278, 'Rovelli Gifts', 'Rovelli', 'Giovanni ', '035-640555', 'Via Ludovico il Moro 22', None, 'Bergamo', None, '24100', 'Italy', 1401, Decimal('119600.00')),
 (282, 'Souveniers And Things Co.', 'Huxley', 'Adrian', '+61 2 9495 8555', 'Monitor Money Building', '815 Pacific Hwy', 'Chatswood', 'NSW', '2067', 'Australia', 1611, Decimal('93300.00')),
 (286, "Marta's Replicas Co.", 'Hernandez', 'Marta', '6175558555', '39323 Spinnaker Dr.', None, 'Cambridge', 'MA', '51247', 'USA', 1216, Decimal('123700.00')),
 (293, 'BG&E Collectables', 'Harrison', 'Ed', '+41 26 425 50 01', 'Rte des Arsenaux 41 ', None, 'Fribourg', None, '1700', 'Switzerland', None, Decimal('0.00')),
 (298, 'Vida Sport, Ltd', 'Holz', 'Mihael', '0897-034555', 'Grenzacherweg 237', None, 'Genève', None, '1203', 'Switzerland', 1702, Decimal('141300.00')),
 (299, 'Norway Gifts By Mail, Co.', 'Klaeboe', 'Jan', '+47 2212 1555', 'Drammensveien 126A', 'PB 211 Sentrum', 'Oslo', None, 'N 0106', 'Norway  ', 1504, Decimal('95100.00')),
 (303, 'Schuyler Imports', 'Schuyler', 'Bradley', '+31 20 491 9555', 'Kingsfordweg 151', None, 'Amsterdam', None, '1043 GR', 'Netherlands', None, Decimal('0.00')),
 (307, 'Der Hund Imports', 'Andersen', 'Mel', '030-0074555', 'Obere Str. 57', None, 'Berlin', None, '12209', 'Germany', None, Decimal('0.00')),
 (311, 'Oulu Toy Supplies, Inc.', 'Koskitalo', 'Pirkko', '981-443655', 'Torikatu 38', None, 'Oulu', None, '90110', 'Finland', 1501, Decimal('90500.00')),
 (314, 'Petit Auto', 'Dewey', 'Catherine ', '(02) 5554 67', 'Rue Joseph-Bens 532', None, 'Bruxelles', None, 'B-1180', 'Belgium', 1401, Decimal('79900.00')),
 (319, 'Mini Classics', 'Frick', 'Steve', '9145554562', '3758 North Pendale Street', None, 'White Plains', 'NY', '24067', 'USA', 1323, Decimal('102700.00')),
 (320, 'Mini Creations Ltd.', 'Huang', 'Wing', '5085559555', '4575 Hillside Dr.', None, 'New Bedford', 'MA', '50553', 'USA', 1188, Decimal('94500.00')),
 (321, 'Corporate Gift Ideas Co.', 'Brown', 'Julie', '6505551386', '7734 Strong St.', None, 'San Francisco', 'CA', '94217', 'USA', 1165, Decimal('105000.00')),
 (323, 'Down Under Souveniers, Inc', 'Graham', 'Mike', '+64 9 312 5555', '162-164 Grafton Road', 'Level 2', 'Auckland  ', None, None, 'New Zealand', 1612, Decimal('88000.00')),
 (324, 'Stylish Desk Decors, Co.', 'Brown', 'Ann ', '(171) 555-0297', '35 King George', None, 'London', None, 'WX3 6FW', 'UK', 1501, Decimal('77000.00')),
 (328, 'Tekni Collectables Inc.', 'Brown', 'William', '2015559350', '7476 Moss Rd.', None, 'Newark', 'NJ', '94019', 'USA', 1323, Decimal('43000.00')),
 (333, 'Australian Gift Network, Co', 'Calaghan', 'Ben', '61-7-3844-6555', '31 Duncan St. West End', None, 'South Brisbane', 'Queensland', '4101', 'Australia', 1611, Decimal('51600.00')),
 (334, 'Suominen Souveniers', 'Suominen', 'Kalle', '+358 9 8045 555', 'Software Engineering Center', 'SEC Oy', 'Espoo', None, 'FIN-02271', 'Finland', 1501, Decimal('98800.00')),
 (335, 'Cramer Spezialitäten, Ltd', 'Cramer', 'Philip ', '0555-09555', 'Maubelstr. 90', None, 'Brandenburg', None, '14776', 'Germany', None, Decimal('0.00')),
 (339, 'Classic Gift Ideas, Inc', 'Cervantes', 'Francisca', '2155554695', '782 First Street', None, 'Philadelphia', 'PA', '71270', 'USA', 1188, Decimal('81100.00')),
 (344, 'CAF Imports', 'Fernandez', 'Jesus', '+34 913 728 555', 'Merchants House', "27-30 Merchant's Quay", 'Madrid', None, '28023', 'Spain', 1702, Decimal('59600.00')),
 (347, "Men 'R' US Retailers, Ltd.", 'Chandler', 'Brian', '2155554369', '6047 Douglas Av.', None, 'Los Angeles', 'CA', '91003', 'USA', 1166, Decimal('57700.00')),
 (348, 'Asian Treasures, Inc.', 'McKenna', 'Patricia ', '2967 555', '8 Johnstown Road', None, 'Cork', 'Co. Cork', None, 'Ireland', None, Decimal('0.00')),
 (350, 'Marseille Mini Autos', 'Lebihan', 'Laurence ', '91.24.4555', '12, rue des Bouchers', None, 'Marseille', None, '13008', 'France', 1337, Decimal('65000.00')),
 (353, 'Reims Collectables', 'Henriot', 'Paul ', '26.47.1555', "59 rue de l'Abbaye", None, 'Reims', None, '51100', 'France', 1337, Decimal('81100.00')),
 (356, 'SAR Distributors, Co', 'Kuger', 'Armand', '+27 21 550 3555', '1250 Pretorius Street', None, 'Hatfield', 'Pretoria', '0028', 'South Africa', None, Decimal('0.00')),
 (357, 'GiftsForHim.com', 'MacKinlay', 'Wales', '64-9-3763555', '199 Great North Road', None, 'Auckland', None, None, 'New Zealand', 1612, Decimal('77700.00')),
 (361, 'Kommission Auto', 'Josephs', 'Karin', '0251-555259', 'Luisenstr. 48', None, 'Münster', None, '44087', 'Germany', None, Decimal('0.00')),
 (362, 'Gifts4AllAges.com', 'Yoshido', 'Juri', '6175559555', '8616 Spinnaker Dr.', None, 'Boston', 'MA', '51003', 'USA', 1216, Decimal('41900.00')),
 (363, 'Online Diecast Creations Co.', 'Young', 'Dorothy', '6035558647', '2304 Long Airport Avenue', None, 'Nashua', 'NH', '62005', 'USA', 1216, Decimal('114200.00')),
 (369, 'Lisboa Souveniers, Inc', 'Rodriguez', 'Lino ', '(1) 354-2555', 'Jardim das rosas n. 32', None, 'Lisboa', None, '1675', 'Portugal', None, Decimal('0.00')),
 (376, 'Precious Collectables', 'Urs', 'Braun', '0452-076555', 'Hauptstr. 29', None, 'Bern', None, '3012', 'Switzerland', 1702, Decimal('0.00')),
 (379, 'Collectables For Less Inc.', 'Nelson', 'Allen', '6175558555', '7825 Douglas Av.', None, 'Brickhaven', 'MA', '58339', 'USA', 1188, Decimal('70700.00')),
 (381, 'Royale Belge', 'Cartrain', 'Pascale ', '(071) 23 67 2555', 'Boulevard Tirou, 255', None, 'Charleroi', None, 'B-6000', 'Belgium', 1401, Decimal('23500.00')),
 (382, 'Salzburg Collectables', 'Pipps', 'Georg ', '6562-9555', 'Geislweg 14', None, 'Salzburg', None, '5020', 'Austria', 1401, Decimal('71700.00')),
 (385, 'Cruz & Sons Co.', 'Cruz', 'Arnold', '+63 2 555 3587', '15 McCallum Street', 'NatWest Center #13-03', 'Makati City', None, '1227 MM', 'Philippines', 1621, Decimal('81500.00')),
 (386, "L'ordine Souveniers", 'Moroni', 'Maurizio ', '0522-556555', 'Strada Provinciale 124', None, 'Reggio Emilia', None, '42100', 'Italy', 1401, Decimal('121400.00')),
 (398, 'Tokyo Collectables, Ltd', 'Shimamura', 'Akiko', '+81 3 3584 0555', '2-2-8 Roppongi', None, 'Minato-ku', 'Tokyo', '106-0032', 'Japan', 1621, Decimal('94400.00')),
 (406, 'Auto Canal+ Petit', 'Perrier', 'Dominique', '(1) 47.55.6555', '25, rue Lauriston', None, 'Paris', None, '75016', 'France', 1337, Decimal('95000.00')),
 (409, 'Stuttgart Collectable Exchange', 'Müller', 'Rita ', '0711-555361', 'Adenauerallee 900', None, 'Stuttgart', None, '70563', 'Germany', None, Decimal('0.00')),
 (412, 'Extreme Desk Decorations, Ltd', 'McRoy', 'Sarah', '04 499 9555', '101 Lambton Quay', 'Level 11', 'Wellington', None, None, 'New Zealand', 1612, Decimal('86800.00')),
 (415, 'Bavarian Collectables Imports, Co.', 'Donnermeyer', 'Michael', ' +49 89 61 08 9555', 'Hansastr. 15', None, 'Munich', None, '80686', 'Germany', 1504, Decimal('77000.00')),
 (424, 'Classic Legends Inc.', 'Hernandez', 'Maria', '2125558493', '5905 Pompton St.', 'Suite 750', 'NYC', 'NY', '10022', 'USA', 1286, Decimal('67500.00')),
 (443, 'Feuer Online Stores, Inc', 'Feuer', 'Alexander ', '0342-555176', 'Heerstr. 22', None, 'Leipzig', None, '04179', 'Germany', None, Decimal('0.00')),
 (447, 'Gift Ideas Corp.', 'Lewis', 'Dan', '2035554407', '2440 Pompton St.', None, 'Glendale', 'CT', '97561', 'USA', 1323, Decimal('49700.00')),
 (448, 'Scandinavian Gift Ideas', 'Larsson', 'Martha', '0695-34 6555', 'Åkergatan 24', None, 'Bräcke', None, 'S-844 67', 'Sweden', 1504, Decimal('116400.00')),
 (450, 'The Sharp Gifts Warehouse', 'Frick', 'Sue', '4085553659', '3086 Ingle Ln.', None, 'San Jose', 'CA', '94217', 'USA', 1165, Decimal('77600.00')),
 (452, 'Mini Auto Werke', 'Mendel', 'Roland ', '7675-3555', 'Kirchgasse 6', None, 'Graz', None, '8010', 'Austria', 1401, Decimal('45300.00')),
 (455, 'Super Scale Inc.', 'Murphy', 'Leslie', '2035559545', '567 North Pendale Street', None, 'New Haven', 'CT', '97823', 'USA', 1286, Decimal('95400.00')),
 (456, 'Microscale Inc.', 'Choi', 'Yu', '2125551957', '5290 North Pendale Street', 'Suite 200', 'NYC', 'NY', '10022', 'USA', 1286, Decimal('39800.00')),
 (458, 'Corrida Auto Replicas, Ltd', 'Sommer', 'Martín ', '(91) 555 22 82', 'C/ Araquil, 67', None, 'Madrid', None, '28023', 'Spain', 1702, Decimal('104600.00')),
 (459, 'Warburg Exchange', 'Ottlieb', 'Sven ', '0241-039123', 'Walserweg 21', None, 'Aachen', None, '52066', 'Germany', None, Decimal('0.00')),
 (462, 'FunGiftIdeas.com', 'Benitez', 'Violeta', '5085552555', '1785 First Street', None, 'New Bedford', 'MA', '50553', 'USA', 1216, Decimal('85800.00')),
 (465, 'Anton Designs, Ltd.', 'Anton', 'Carmen', '+34 913 728555', 'c/ Gobelas, 19-1 Urb. La Florida', None, 'Madrid', None, '28023', 'Spain', None, Decimal('0.00')),
 (471, 'Australian Collectables, Ltd', 'Clenahan', 'Sean', '61-9-3844-6555', '7 Allen Street', None, 'Glen Waverly', 'Victoria', '3150', 'Australia', 1611, Decimal('60300.00')),
 (473, 'Frau da Collezione', 'Ricotti', 'Franco', '+39 022515555', '20093 Cologno Monzese', 'Alessandro Volta 16', 'Milan', None, None, 'Italy', 1401, Decimal('34800.00')),
 (475, 'West Coast Collectables Co.', 'Thompson', 'Steve', '3105553722', '3675 Furth Circle', None, 'Burbank', 'CA', '94019', 'USA', 1166, Decimal('55400.00')),
 (477, 'Mit Vergnügen & Co.', 'Moos', 'Hanna ', '0621-08555', 'Forsterstr. 57', None, 'Mannheim', None, '68306', 'Germany', None, Decimal('0.00')),
 (480, 'Kremlin Collectables, Co.', 'Semenov', 'Alexander ', '+7 812 293 0521', '2 Pobedy Square', None, 'Saint Petersburg', None, '196143', 'Russia', None, Decimal('0.00')),
 (481, 'Raanan Stores, Inc', 'Altagar,G M', 'Raanan', '+ 972 9 959 8555', '3 Hagalim Blv.', None, 'Herzlia', None, '47625', 'Israel', None, Decimal('0.00')),
 (484, 'Iberia Gift Imports, Corp.', 'Roel', 'José Pedro ', '(95) 555 82 82', 'C/ Romero, 33', None, 'Sevilla', None, '41101', 'Spain', 1702, Decimal('65700.00')),
 (486, 'Motor Mint Distributors Inc.', 'Salazar', 'Rosa', '2155559857', '11328 Douglas Av.', None, 'Philadelphia', 'PA', '71270', 'USA', 1323, Decimal('72600.00')),
 (487, 'Signal Collectibles Ltd.', 'Taylor', 'Sue', '4155554312', '2793 Furth Circle', None, 'Brisbane', 'CA', '94217', 'USA', 1165, Decimal('60300.00')),
 (489, 'Double Decker Gift Stores, Ltd', 'Smith', 'Thomas ', '(171) 555-7555', '120 Hanover Sq.', None, 'London', None, 'WA1 1DP', 'UK', 1501, Decimal('43300.00')),
 (495, 'Diecast Collectables', 'Franco', 'Valarie', '6175552555', '6251 Ingle Ln.', None, 'Boston', 'MA', '51003', 'USA', 1188, Decimal('85100.00')),
 (496, "Kelly's Gift Shop", 'Snowden', 'Tony', '+64 9 5555500', "Arenales 1938 3'A'", None, 'Auckland  ', None, None, 'New Zealand', 1612, Decimal('110000.00'))]

- That is kind of "flat-ish" and not very "documenty."


- Let's documenty those things.

In [33]:
customers_docs = []

for c in customers:
    
    new_doc = {
        "customerNumber": c["customerNumber"],
        "customerName": c["customerName"],
        "contact": {
            "lastName": c["contactLastName"],
            "firstName": c["contactFirstName"]
        },
        "phone": c["phone"],
        "address": {
            "addressLine1": c["addressLine1"],
            "addressLine2": c["addressLine2"],
            "city": c["city"],
            "state": c["state"],
            "country": c["country"],
            "postalCode": c["postalCode"]
        },
        "salesRepNumber": c["salesRepEmployeeNumber"],
        "creditLimit": float(c["creditLimit"])
    }
    
    customers_docs.append(new_doc)

In [34]:
customers_docs[0:1]

[{'customerNumber': 103,
  'customerName': 'Atelier graphique',
  'contact': {'lastName': 'Schmitt', 'firstName': 'Carine '},
  'phone': '40.32.2555',
  'address': {'addressLine1': '54, rue Royale',
   'addressLine2': None,
   'city': 'Nantes',
   'state': None,
   'country': 'France',
   'postalCode': '44000'},
  'salesRepNumber': 1370,
  'creditLimit': 21000.0}]

- And then let's make a collection for customers ... ...

In [35]:
customer_collection = mongo_conn['classicmodels']['customers']

In [36]:
for d in customers_docs:
    customer_collection.insert_one(d)

### Let Find the Customers in France

In [37]:
result = customer_collection.find(
    {"address.country": "France" }
)

In [38]:
result = list(result)
result

[{'_id': ObjectId('636d5edc029bc8cf2e2bd767'),
  'customerNumber': 103,
  'customerName': 'Atelier graphique',
  'contact': {'lastName': 'Schmitt', 'firstName': 'Carine '},
  'phone': '40.32.2555',
  'address': {'addressLine1': '54, rue Royale',
   'addressLine2': None,
   'city': 'Nantes',
   'state': None,
   'country': 'France',
   'postalCode': '44000'},
  'salesRepNumber': 1370,
  'creditLimit': 21000.0},
 {'_id': ObjectId('636d5edc029bc8cf2e2bd76a'),
  'customerNumber': 119,
  'customerName': 'La Rochelle Gifts',
  'contact': {'lastName': 'Labrune', 'firstName': 'Janine '},
  'phone': '40.67.8555',
  'address': {'addressLine1': '67, rue des Cinquante Otages',
   'addressLine2': None,
   'city': 'Nantes',
   'state': None,
   'country': 'France',
   'postalCode': '44000'},
  'salesRepNumber': 1370,
  'creditLimit': 118200.0},
 {'_id': ObjectId('636d5edd029bc8cf2e2bd774'),
  'customerNumber': 146,
  'customerName': 'Saveley & Henriot, Co.',
  'contact': {'lastName': 'Saveley', 'firstName': 'Mary '},
  'phone': '78.32.5555',
  'address': {'addressLine1': '2, rue du Commerce',
   'addressLine2': None,
   'city': 'Lyon',
   'state': None,
   'country': 'France',
   'postalCode': '69004'},
  'salesRepNumber': 1337,
  'creditLimit': 123900.0},
 {'_id': ObjectId('636d5edd029bc8cf2e2bd77d'),
  'customerNumber': 171,
  'customerName': 'Daedalus Designs Imports',
  'contact': {'lastName': 'Rancé', 'firstName': 'Martine '},
  'phone': '20.16.1555',
  'address': {'addressLine1': '184, chaussée de Tournai',
   'addressLine2': None,
   'city': 'Lille',
   'state': None,
   'country': 'France',
   'postalCode': '59000'},
  'salesRepNumber': 1370,
  'creditLimit': 82900.0},
 {'_id': ObjectId('636d5edd029bc8cf2e2bd77e'),
  'customerNumber': 172,
  'customerName': "La Corne D'abondance, Co.",
  'contact': {'lastName': 'Bertrand', 'firstName': 'Marie'},
  'phone': '(1) 42.34.2555',
  'address': {'addressLine1': '265, boulevard Charonne',
   'addressLine2': None,
   'city': 'Paris',
   'state': None,
   'country': 'France',
   'postalCode': '75012'},
  'salesRepNumber': 1337,
  'creditLimit': 84300.0},
 {'_id': ObjectId('636d5edd029bc8cf2e2bd78c'),
  'customerNumber': 209,
  'customerName': 'Mini Caravy',
  'contact': {'lastName': 'Citeaux', 'firstName': 'Frédérique '},
  'phone': '88.60.1555',
  'address': {'addressLine1': '24, place Kléber',
   'addressLine2': None,
   'city': 'Strasbourg',
   'state': None,
   'country': 'France',
   'postalCode': '67000'},
  'salesRepNumber': 1370,
  'creditLimit': 53800.0},
 {'_id': ObjectId('636d5ede029bc8cf2e2bd796'),
  'customerNumber': 242,
  'customerName': 'Alpha Cognac',
  'contact': {'lastName': 'Roulet', 'firstName': 'Annette '},
  'phone': '61.77.6555',
  'address': {'addressLine1': '1 rue Alsace-Lorraine',
   'addressLine2': None,
   'city': 'Toulouse',
   'state': None,
   'country': 'France',
   'postalCode': '31000'},
  'salesRepNumber': 1370,
  'creditLimit': 61100.0},
 {'_id': ObjectId('636d5ede029bc8cf2e2bd799'),
  'customerNumber': 250,
  'customerName': 'Lyon Souveniers',
  'contact': {'lastName': 'Da Silva', 'firstName': 'Daniel'},
  'phone': '+33 1 46 62 7555',
  'address': {'addressLine1': '27 rue du Colonel Pierre Avia',
   'addressLine2': None,
   'city': 'Paris',
   'state': None,
   'country': 'France',
   'postalCode': '75508'},
  'salesRepNumber': 1337,
  'creditLimit': 68100.0},
 {'_id': ObjectId('636d5ede029bc8cf2e2bd79a'),
  'customerNumber': 256,
  'customerName': 'Auto Associés & Cie.',
  'contact': {'lastName': 'Tonini', 'firstName': 'Daniel '},
  'phone': '30.59.8555',
  'address': {'addressLine1': "67, avenue de l'Europe",
   'addressLine2': None,
   'city': 'Versailles',
   'state': None,
   'country': 'France',
   'postalCode': '78000'},
  'salesRepNumber': 1370,
  'creditLimit': 77900.0},
 {'_id': ObjectId('636d5edf029bc8cf2e2bd7b6'),
  'customerNumber': 350,
  'customerName': 'Marseille Mini Autos',
  'contact': {'lastName': 'Lebihan', 'firstName': 'Laurence '},
  'phone': '91.24.4555',
  'address': {'addressLine1': '12, rue des Bouchers',
   'addressLine2': None,
   'city': 'Marseille',
   'state': None,
   'country': 'France',
   'postalCode': '13008'},
  'salesRepNumber': 1337,
  'creditLimit': 65000.0},
 {'_id': ObjectId('636d5edf029bc8cf2e2bd7b7'),
  'customerNumber': 353,
  'customerName': 'Reims Collectables',
  'contact': {'lastName': 'Henriot', 'firstName': 'Paul '},
  'phone': '26.47.1555',
  'address': {'addressLine1': "59 rue de l'Abbaye",
   'addressLine2': None,
   'city': 'Reims',
   'state': None,
   'country': 'France',
   'postalCode': '51100'},
  'salesRepNumber': 1337,
  'creditLimit': 81100.0},
 {'_id': ObjectId('636d5edf029bc8cf2e2bd7c5'),
  'customerNumber': 406,
  'customerName': 'Auto Canal+ Petit',
  'contact': {'lastName': 'Perrier', 'firstName': 'Dominique'},
  'phone': '(1) 47.55.6555',
  'address': {'addressLine1': '25, rue Lauriston',
   'addressLine2': None,
   'city': 'Paris',
   'state': None,
   'country': 'France',
   'postalCode': '75016'},
  'salesRepNumber': 1337,
  'creditLimit': 95000.0}]

### Let's Go Totally Nuts!

- Create a ```view``` from an aggregation.

In [39]:
db = mongo_conn["classicmodels"]
db

Database(MongoClient(host=['cluster0-shard-00-02.t8qdk.mongodb.net:27017', 'cluster0-shard-00-01.t8qdk.mongodb.net:27017', 'cluster0-shard-00-00.t8qdk.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', replicaset='atlas-hflv73-shard-0', tls=True), 'classicmodels')

In [40]:
pipeline = \
   [
        {
            '$match': {
                'status': {
                    '$nin': [
                        'Cancelled', 'On Hold', 'In Process'
                    ]
                }
            }
        }, {
            '$unwind': {
                'path': '$orderLines', 
                'preserveNullAndEmptyArrays': True
            }
        }, {
            '$project': {
                'customerNumber': 1, 
                'orderNumber': 1, 
                'status': 1, 
                'quantityOrdered': '$orderLines.quantityOrdered', 
                'priceEach': '$orderLines.priceEach', 
                'lineValue': {
                    '$multiply': [
                        '$orderLines.quantityOrdered', '$orderLines.priceEach'
                    ]
                }
            }
        }, {
            '$group': {
                '_id': '$customerNumber', 
                'totalValue': {
                    '$sum': '$lineValue'
                }
            }
        }, {
            '$project': {
                '_id': 0, 
                'customerNumber': '$_id', 
                'totalValue': 1
            }
        }, {
            '$sort': {
                'totalValue': -1
            }
        }
    ]

In [48]:
db.command({
    "create": "customer_revenue_view",
    "viewOn": "ordersall", 
    "pipeline": pipeline
})

{'ok': 1.0,
 '$clusterTime': {'clusterTime': Timestamp(1668112274, 1),
  'signature': {'hash': b'\xea\xbf\xca\x0f\xdcs\xec\x9eC\x86\xa5\xa5\xcd\x87\x13z\xac\xd9[\xbd',
   'keyId': 7102840227760177155}},
 'operationTime': Timestamp(1668112274, 1)}

- Let's test it ...

In [50]:
filter={}

result = mongo_conn['classicmodels']['customer_revenue_view'].find(
  filter=filter
)

In [51]:
result = list(result)
result_df = pd.DataFrame(result)

In [52]:
result_df

    totalValue  customerNumber
0    744313.88             141
1    584188.24             124
2    180585.07             114
3    177913.95             151
4    156251.03             148
..         ...             ...
93    29217.18             381
94    25358.32             473
95    22314.36             103
96    21554.26             198
97     7918.60             219

[98 rows x 2 columns]

In [53]:
result_df = result_df[["customerNumber", "totalValue"]]
result_df

    customerNumber  totalValue
0              141   744313.88
1              124   584188.24
2              114   180585.07
3              151   177913.95
4              148   156251.03
..             ...         ...
93             381    29217.18
94             473    25358.32
95             103    22314.36
96             198    21554.26
97             219     7918.60

[98 rows x 2 columns]

- That's cool, but ... I want some customer info! That sounds like some kind of "lookup thingy."

In [54]:
# Requires the PyMongo package.
# https://api.mongodb.com/python/current

result = mongo_conn['classicmodels']['customers'].aggregate([
    {
        '$lookup': {
            'from': 'customer_revenue_view', 
            'localField': 'customerNumber', 
            'foreignField': 'customerNumber', 
            'as': 'total_revenue'
        }
    }, {
        '$project': {
            'customerNumber': 1, 
            'customerName': 1, 
            'total_revenue': {
                '$arrayElemAt': [
                    '$total_revenue', 0
                ]
            }
        }
    }, {
        '$project': {
            'customerNumber': 1, 
            'customerName': 1, 
            'total_revenue': '$total_revenue.totalValue', 
            '_id': 0
        }
    }
])

In [55]:
cool_df = pd.DataFrame(list(result))
cool_df = cool_df[["customerNumber", "customerName", "total_revenue"]]
cool_df

     customerNumber                    customerName  total_revenue
0               103               Atelier graphique       22314.36
1               112              Signal Gift Stores       80180.98
2               114      Australian Collectors, Co.      180585.07
3               119               La Rochelle Gifts      116949.68
4               121              Baane Mini Imports      104224.79
..              ...                             ...            ...
117             486    Motor Mint Distributors Inc.       77726.59
118             487        Signal Collectibles Ltd.       42570.37
119             489  Double Decker Gift Stores, Ltd       29586.15
120             495            Diecast Collectables       65541.74
121             496               Kelly's Gift Shop      114497.19

[122 rows x 3 columns]